### PR TITLE
fix send function for direct

### PR DESCRIPTION
**Pull request by i0seph**
send last bit to first data pin

### CODE REVIEW

**Comment by MajicDesigns** [comment]
I do not understand the comment. Can you explain why the change in index for the bit is necessary from what was originally in the library?

**Comment by i0seph** [comment]
I tried to make sound using http://danceswithferrets.org/geekblog/?p=93 article. this work is good. next, I wanted to add midi function, so I found your source. but this source dit not work on esp32, then I inspect code,  I found send byte function is diffrent. that is first bit , first set, your code is first bit , last set. I changed first bit, first set. then I heard good sound :),  so I sent my code. (this problem is same on arduino.)

**Comment by MajicDesigns** [comment]
OK. So this means that your project's data bus is just wired in reverse from from what this library expects it to be. You can equally just define the data bus pin numbers in the array provided from the sketch in reverse order and there is no need to change the library.
Thanks for the contribution but I will stay with the code as it is because it works consistently with the way that the hardware connections are described in the documentation for the library.

**Comment by i0seph** [comment]
Yes, this prblem can be fixed to change pin connect order.
but, 
in Your example codes,
#if USE_DIRECT
// All the pins directly connected to D0-D7 on the IC, in sequential order 
// so that pin D_PIN[0] is connected to D0, D_PIN[1] to D1, etc.
const uint8_t D_PIN[] = { A0, A1, A2, A3, 4, 5, 6, 7 };

if someone connect like this comment, it may be not work correct.

**Comment by MajicDesigns** [comment]
The comment is correct. The manufacturer's datasheet for the SN74689 (see http://www.primrosebank.net/computers/mtx/projects/mtxplus/data/SN76489.pdf if you don't already have one) is the correct reference for how the pins on the IC are numbered. The reference you gave (http://danceswithferrets.org/geekblog/?p=93) above has the data bus pins D0-D7 numbered in reverse order from the datasheet.

**Comment by i0seph** [comment]
Thanks!
This is my mistake. I missed to check original datasheet.

**Pull request closed without merging**
